### PR TITLE
hideFromIndex() in Laravel Nova style.

### PR DESCRIPTION
**Pull request by 4n70w4**
Example: InlinePanel::make($this, $request, 'Chart Name')->hideFromIndex(),

### CODE REVIEW

**Comment by dvanscott** [comment]
@4n70w4 Thanks for the contribution! We'll take a look at this as soon as we can.

**Comment by navneetrai** [comment]
@dvanscott Do you think this is necessary? we already have this as an argument in constructor

**Comment by 4n70w4** [comment]
All Nova fields have this method. See `\Laravel\Nova\Fields\FieldElement::hideFromIndex`

**Comment by 4n70w4** [comment]
Passing 6+ parameters to a constructor is a bit antipattern =)

**Comment by 4n70w4** [comment]
Hi! Any news?

**Comment by wilkerwma** [comment]
Hi @4n70w4 we are closing this in favor of this one: https://github.com/kirschbaum-development/nova-chartjs/pull/67/ 
This new PR is based on your changes and we really appreciate your contribution. 
Sorry for the delay on this approval.

**Pull request closed without merging**
